#!/bin/bash
# AI-assistant PR creation script with validation

# Validate branch exists and isn't main
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" = "main" ]; then
  echo "ERROR: Cannot create PR from main branch"
  exit 1
fi

# Verify branch name pattern
if [[ ! "$CURRENT_BRANCH" =~ ^(feature|fix|docs|refactor|ci|chore|test)/[a-z0-9-]+$ ]]; then
  echo "ERROR: Branch name doesn't follow required pattern"
  exit 1
fi

# Create PR with standardized format
BRANCH_TYPE=$(echo "$CURRENT_BRANCH" | cut -d/ -f1)
BRANCH_DESC=$(echo "$CURRENT_BRANCH" | cut -d/ -f2 | tr '-' ' ')
PR_TITLE="$BRANCH_TYPE: $(echo "$BRANCH_DESC" | sed 's/\b\(.\)/\u\1/g')"

gh pr create --title "$PR_TITLE" --body "## Changes
$(git log --pretty=format:'* %s' main..$CURRENT_BRANCH | grep -v 'Merge')

## Checklist
- [ ] Tests added/updated
- [ ] Documentation updated
- [ ] CHANGELOG.md updated

Generated by Claude"

echo "PR created successfully with title: $PR_TITLE"