name: Changelog Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'

jobs:
  check-changelog:
    name: Check Changelog is Versioned
    runs-on: ubuntu-latest
    # Only run this check on PRs to main branch
    if: github.base_ref == 'main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check changelog meets format requirements
        run: |
          # Verify CHANGELOG.md exists
          if [ ! -f "CHANGELOG.md" ]; then
            echo "::error::CHANGELOG.md not found"
            exit 1
          fi
          
          # Check if there's an Unreleased section
          if ! grep -q "## \[Unreleased\]" CHANGELOG.md; then
            echo "::error::CHANGELOG.md must have an [Unreleased] section at the top"
            exit 1
          fi
          
          # Verify there's a proper version format in the file (semantic versioning)
          if ! grep -q "## \[[0-9]\+\.[0-9]\+\.[0-9]\+\(-[0-9]\+\)\?\]" CHANGELOG.md; then
            echo "::error::CHANGELOG.md must have at least one properly versioned section (e.g., ## [1.2.3] or ## [1.2.3-1])"
            exit 1
          fi
          
          # Check that the Unreleased section is followed by a version section
          if ! awk '/^## \[Unreleased\]/,/^## \[[0-9]/' CHANGELOG.md | grep -q "^## \[[0-9]"; then
            echo "::error::The [Unreleased] section must be followed by a version section"
            exit 1
          fi
          
          echo "✅ CHANGELOG.md meets format requirements"