name: Dependency Management

on:
  schedule:
    - cron: '0 0 * * 1'  # Run at midnight every Monday
  workflow_dispatch:  # Allow manual triggering

jobs:
  dependency-audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci --prefer-offline
        
      - name: Run npm audit
        run: npm audit
        continue-on-error: true
        
      - name: Check outdated dependencies
        run: npm outdated || true
        
  dependency-report:
    name: Generate Dependency Report
    runs-on: ubuntu-latest
    needs: dependency-audit
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci --prefer-offline
        
      - name: Install license-checker
        run: npm install -g license-checker
        
      - name: Generate license report
        run: |
          mkdir -p reports
          license-checker --json --out reports/licenses.json
        
      - name: Upload report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dependency-reports
          path: reports/
          retention-days: 30