name: Hello World

on:
  push:
    branches: [ test/github-actions-hello-world ]
  workflow_dispatch:

jobs:
  hello-world:
    name: Hello World Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Hello World
        run: |
          echo "Hello, World!"
          echo "This is a test of GitHub Actions"
          echo "Current date is $(date)"
          echo "Repository: $GITHUB_REPOSITORY"
          
      - name: Environment Info
        run: |
          echo "Node.js version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "GitHub Actions info:"
          echo "  Runner: $RUNNER_OS"
          echo "  Workflow: $GITHUB_WORKFLOW"
          echo "  Event: $GITHUB_EVENT_NAME"
          echo "  Ref: $GITHUB_REF"