name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main]

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate branch name and PR title
        run: |
          # Get branch name
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch: $BRANCH_NAME"
          
          # Check branch name format
          if ! echo "$BRANCH_NAME" | grep -E "^(feature|fix|docs|refactor|ci|chore|test)/[a-z0-9-]+" > /dev/null; then
            echo "Error: Branch name doesn't follow the pattern: (feature|fix|docs|refactor|ci|chore|test)/name"
            echo "Examples: feature/login-page, fix/auth-bug"
            exit 1
          fi
          
          # Get PR title
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $PR_TITLE"
          
          # Check PR title format (conventional commits)
          if ! echo "$PR_TITLE" | grep -Ei "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\([a-z0-9-]+\\))?: [A-Za-z]" > /dev/null; then
            echo "Error: PR title must follow the conventional commit format"
            echo "Examples: 'feat: Add user login' or 'fix(auth): Fix password reset'"
            exit 1
          fi
          
          echo "Validation passed: Branch name and PR title are correctly formatted"
  
  check-changelog:
    name: Check CHANGELOG
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check CHANGELOG.md update
        run: |
          # Get PR title for type detection
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $PR_TITLE"
          
          # Skip this check for specific PR types
          if echo "$PR_TITLE" | grep -E "^(docs|chore|ci|test):" > /dev/null; then
            echo "PR type doesn't require CHANGELOG update, skipping check"
            exit 0
          fi
          
          # Check if CHANGELOG.md was modified
          if ! git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep "CHANGELOG.md" > /dev/null; then
            echo "Error: CHANGELOG.md was not updated"
            echo "Please add an entry for your changes to the [Unreleased] section of CHANGELOG.md"
            exit 1
          fi
          
          echo "CHANGELOG.md has been updated correctly"