name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main]

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Checking branch: $BRANCH_NAME"
          
          if [[ ! "$BRANCH_NAME" =~ ^(feature|fix|docs|refactor|ci|chore|test)/[a-z0-9-]+$ ]]; then
            echo "::error::Branch name doesn't follow the pattern: (feature|fix|docs|refactor|ci|chore|test)/[a-z0-9-]+"
            exit 1
          fi
          
          echo "Branch name is valid"
  
  check-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate PR title format
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Checking PR title: $PR_TITLE"
          
          # Check for conventional commit format
          if ! [[ "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(:|\([a-z0-9-]+\):) ]]; then
            echo "::error::PR title must follow the conventional commit format"
            echo "::error::Examples: 'feat: Add user login' or 'fix(auth): Fix password reset'"
            exit 1
          fi
          
          echo "PR title format is valid"
  
  check-changelog:
    name: Check CHANGELOG
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check CHANGELOG.md update
        run: |
          # Skip this check for specific PR types
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" =~ ^(docs:|chore:|ci:|test:) ]]; then
            echo "PR type doesn't require CHANGELOG update, skipping check"
            exit 0
          fi
          
          # Check if CHANGELOG.md was modified
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "CHANGELOG.md"
          if [ $? -ne 0 ]; then
            echo "::error::CHANGELOG.md was not updated. Please add an entry for your changes."
            exit 1
          fi
          
          echo "CHANGELOG.md has been updated"